# Generated by Django 3.1.4 on 2021-01-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(default='Tzourhs', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('address_line', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_charging_categories', models.IntegerField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cluster')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingPoint',
            fields=[
                ('owner', models.CharField(default='Tzourhs', max_length=100)),
                ('charging_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('usage_type_id', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('usage_cost', models.FloatField()),
                ('kw_power', models.FloatField()),
                ('volts_power', models.FloatField()),
                ('amps_power', models.FloatField()),
                ('charging_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.chargingstation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.location')),
            ],
        ),
    ]
