# Generated by Django 3.1.4 on 2021-01-06 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('telephone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('title', models.CharField(max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('town', models.CharField(max_length=20)),
                ('address_line', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='Tzourhs', max_length=15)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cluster')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.IntegerField(choices=[(7, 'Avcon Connector'), (4, 'Blue Commando (2P+E)'), (3, 'BS1363 3 Pin 13 Amp'), (32, 'CCS (Type 1)'), (33, 'CCS (Type 2)'), (16, 'CEE 3 Pin'), (17, 'CEE 5 Pin'), (28, 'CEE 7/4 - Schuko - Type F'), (23, 'CEE 7/5'), (18, 'CEE+ 7 Pin'), (2, 'CHAdeMO'), (13, 'Europlug 2-Pin (CEE 7/16)'), (1038, 'GB-T AC - GB/T 20234.2 (Socket)'), (1039, 'GB-T AC - GB/T 20234.2 (Tethered Cable)'), (1040, 'GB-T DC - GB/T 20234.3'), (34, 'IEC 60309 3-pin'), (35, 'IEC 60309 5-pin'), (5, 'LP Inductive'), (10, 'NEMA 14-30'), (11, 'NEMA 14-50'), (22, 'NEMA 5-15R'), (9, 'NEMA 5-20R'), (15, 'NEMA 6-15'), (14, 'NEMA 6-20'), (1042, 'NEMA TT-30R'), (36, 'SCAME Type 3A (Low Power)'), (26, 'SCAME Type 3C (Schneider-Legrand)'), (6, 'SP Inductive'), (1037, 'T13 - SEC1011 ( Swiss domestic 3-pin ) - Type J'), (30, 'Tesla (Model S/X)'), (8, 'Tesla (Roadster)'), (31, 'Tesla Battery Swap'), (27, 'Tesla Supercharger'), (1041, 'Three Phase 5-Pin (AS/NZ 3123)'), (1, 'Type 1 (J1772)'), (25, 'Type 2 (Socket Only)'), (1036, 'Type 2 (Tethered Connector)'), (29, 'Type I (AS 3112)'), (0, 'Unknown'), (24, 'Wireless Charging'), (21, 'XLR Plug (4 pin)')])),
                ('current_type', models.IntegerField(choices=[(1, 'AC - Single Phase'), (2, 'AC - Three Phase'), (3, 'DC')])),
                ('status_type', models.IntegerField(choices=[(0, 'Unknown'), (10, 'Currently Available (Automated Status)'), (20, 'Currently In Use (Automated Status)'), (30, 'Temporarily Unavailable'), (50, 'Operational'), (75, 'Partly Operational (Mixed)'), (100, 'Not Operational'), (150, 'Planned For Future Date'), (200, 'Removed (Decommissioned)'), (210, 'Removed (Duplicate Listing)')])),
                ('Type', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('usage_type_id', models.IntegerField(choices=[(0, 'Unknown'), (6, 'Private - For Staff'), (2, 'Private - Restricted Access'), (3, 'Privately Owned - Notice Required'), (1, 'Public'), (4, 'Public - Membership Required'), (7, 'Public - Notice Required'), (5, 'Public - Pay At Location')])),
                ('kw_power', models.IntegerField(choices=[(1, 'Under 2 kW'), (2, 'Over 2 kW'), (3, 'Over 40 kW')])),
                ('usage_cost', models.FloatField()),
                ('volts_power', models.FloatField()),
                ('amps_power', models.FloatField()),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.chargingstation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.location')),
            ],
        ),
    ]
