# Generated by Django 3.1.5 on 2021-03-05 13:03

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="dc_ports",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("ccs", "Combined Charging System"),
                    ("chademo", "Chademo"),
                    ("tesla_ccs", "Tesla Combined Charging System"),
                    ("tesla_suc", "Tesla Supercharger"),
                    ("none", "None"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleowner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_owner",
                to="common.user",
            ),
        ),
    ]
