# Generated by Django 3.1.5 on 2021-02-21 10:37

import django_countries.fields
import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="telephone",
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
