# Generated by Django 3.1.5 on 2021-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(default='DEH', max_length=20),
            preserve_default=False,
        ),
    ]
