# Generated by Django 3.1.5 on 2021-01-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_provider_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.provider'),
        ),
    ]
