# Generated by Django 3.1.6 on 2021-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_session_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingpoint',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=2),
        ),
    ]
