# Generated by Django 3.1.5 on 2021-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20210221_1237"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="ac_charging_power",
            field=models.JSONField(null=True),
        ),
    ]
