# Generated by Django 3.1.5 on 2021-02-21 11:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_auto_20210221_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="ac_ports",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("type1", "Type1"), ("type2", "Type2")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="dc_ports",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("ccs", "Combined Charging System"),
                    ("chademo", "Chademo"),
                    ("tesla_ccs", "Tesla Combined Charging System"),
                    ("tesla_suc", "Tesla Supercharger"),
                ],
                max_length=12,
                null=True,
            ),
        ),
    ]
