# Generated by Django 3.1.5 on 2021-03-05 11:08

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_auto_20210221_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="connect_time",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 5, 11, 8, 13, 962493, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
