# Generated by Django 3.1.5 on 2021-03-10 12:06

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_auto_20210305_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingpoint",
            name="amps_power",
            field=models.FloatField(validators=[common.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name="chargingpoint",
            name="usage_cost",
            field=models.FloatField(validators=[common.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name="chargingpoint",
            name="volts_power",
            field=models.FloatField(validators=[common.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name="payment",
            name="cost",
            field=models.FloatField(
                blank=True, validators=[common.validators.validate_positive]
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="ac_charging_power",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="ac_max_power",
            field=models.FloatField(validators=[common.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="average_energy_consumption",
            field=models.FloatField(validators=[common.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="dc_charging_curve",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="dc_max_power",
            field=models.FloatField(
                null=True, validators=[common.validators.validate_positive]
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="usable_battery_size",
            field=models.FloatField(validators=[common.validators.validate_positive]),
        ),
    ]
